### ISSUE TITLE
Позиционирование тултипов

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinRangeSlider#10]
А при позиционировании блоков со значениями вот этими точно не обойтись без js? это усложняет логику, тем более что эти штуки всегда находятся там же, где и сами ползунки. Думаю, было бы лучше положить тултипы прямо в ползунки и позиционировать относительно них уже, тогда можно будет обойтись обычными стилями
![image](https://user-images.githubusercontent.com/46089168/95068522-1220ad00-070e-11eb-99fb-6b0bee0603e2.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
