### ISSUE TITLE
Неиспользуемые элементы

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinRangeSlider#11]
Как я понял, тут при любых настройках слайдера добавляются все элементы, а уже потом в зависимости от них некоторые скрываются через ` display: none; ` . Немного странно, что если пользователь добавит слайдер с 1 бегунком, в разметке их будет 2. Думаю, стоит создавать эти элементы динамически на основании переданных настроек, чтобы в разметке были только используемые элементы
![image](https://user-images.githubusercontent.com/46089168/95069888-0209cd00-0710-11eb-8eb9-0ec254905411.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
