### ISSUE TITLE
Настройки

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinRangeSlider#13]
Не очень понял, зачем для каждого свойства создавать отдельный метод, из-за этого код сильно разрастается. Как тебе вариант сделать 1 объект со всеми настройками, целиком валидировать и отдавать его?
![image](https://user-images.githubusercontent.com/46089168/95071522-734a7f80-0712-11eb-9c6c-3cbb2c79413e.png)

**Comment by wirwl** [comment]
Тут расчёт был такой. Что для инициализации или обновления значения плагина я буду использовать RangeSliderOptions, который по проще. А для внутреннего кода я буду использовать CRangeSliderOptions, который основывается на RangeSliderOptions.

Я в принципе могу вообще CRangeSliderOptions убрать, по моему не очень то он пригодился.

**Comment by wirwl** [comment]
Исправил, можно проверять.
