### ISSUE TITLE
Инлайновый z-index

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinRangeSlider#16]
Было бы лучше заменить тут инлайновую запись z-index на обычные классы и их переключать, динамическое изменение тут на первый взгляд не нужно
![image](https://user-images.githubusercontent.com/46089168/96034539-59274480-0e6a-11eb-9642-8431e75a811f.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
