### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinRangeSlider#3]
Как исправишь, обновляй развернутую страницн, проверяю пока на ней.

1. Слайдеры слишком близко друг с другом
![toclose](https://user-images.githubusercontent.com/51824674/86601385-0dd7dd00-bfc3-11ea-85c0-8dc2aca5a32a.png)

2. Значения в инпутах не меняются при обновлении, вместо движения бегунка начинается перетаскивание шкалы, после отпускания мыши бегунок продолжает двигаться.
![first](https://user-images.githubusercontent.com/51824674/86601619-5d1e0d80-bfc3-11ea-8b5a-e19cde231f09.gif)

3. Начальное значение шага 0, второй раз не сработало переключение шага на 15, после обновления слайдер становится вертикальным и фактические его значения не соответствуют значениям в инпутах.
![second](https://user-images.githubusercontent.com/51824674/86601879-b2f2b580-bfc3-11ea-916a-dc239b088f08.gif)

**Comment by wirwl** [comment]
> 2\. Значения в инпутах не меняются при обновлении, вместо движения бегунка начинается перетаскивание шкалы, после отпускания мыши бегунок продолжает двигаться.

У меня этот баг не воспроизводиться:
![](http://g.recordit.co/Kv4uekUd6D.gif)

**Comment by wirwl** [comment]
> 3\. Начальное значение шага 0, второй раз не сработало переключение шага на 15, после обновления слайдер становится вертикальным и фактические его значения не соответствуют значениям в инпутах.

Аналогично, проблема не возспроизводиться:
![](http://g.recordit.co/eAHXKvaOCT.gif)

**Comment by iatsdotfatr** [comment]
Проверил на десятой винде.
1. Значение from на панели изменяется на 256, у слайдера на 128
![shit](https://user-images.githubusercontent.com/51824674/87953519-f7567900-cacc-11ea-8f65-1d3aca9050af.gif)

2. Никакой реакции на изменение шага, также возможны нулевые и отрицательные значения шага.
![nostep](https://user-images.githubusercontent.com/51824674/87953536-fd4c5a00-cacc-11ea-8fa5-086b960b22c1.gif)

3. После обновления страницы ориентация слайдера меняется, значение на панели нет.
![vertical](https://user-images.githubusercontent.com/51824674/87953824-5ae0a680-cacd-11ea-8944-2faa0f38fb55.gif)

4. Баг с перетаскиванием воспроизводится нерегулярно, можешь пока забить
![bug](https://user-images.githubusercontent.com/51824674/87954719-8fa12d80-cace-11ea-9db9-09ad779992fc.gif)

**Comment by wirwl** [comment]
> 1. Значение from на панели изменяется на 256, у слайдера на 128

Это сработал внутренний валидатор у слайдера, значение from не может быть больше чем to. Поэтому значение from стало равно 128.
Добавил валидацию на уровне Панели. Так же если ввести неправильное значение (слайдер содержит массив значений) то просто возвращается предыдущее значение.



> 2\. Никакой реакции на изменение шага, также возможны нулевые и отрицательные значения шага.

Убрал возможность введения отрицательных значений шага в панели. 0 - это значит что шага нет.



> 3\. После обновления страницы ориентация слайдера меняется, значение на панели нет.

У себя такого не наблюдаю. На приведённой гифке, так же, не вижу того что значения не изменяются, просто у слайдера значения 8 и 256 и после обновления так и должно быть 8 и 256.



> 4\. Баг с перетаскиванием воспроизводится нерегулярно, можешь пока забить

Этот баг вообще не смог воспроизвести, проверял в Хроме, Опере, Файрфоксе. 
Но я добавил preventdefault() для события dragstart - возможно это уберёт этот баг.

Исправил можно проверять.

**Comment by iatsdotfatr** [comment]
> У себя такого не наблюдаю. На приведённой гифке, так же, не вижу того что значения не изменяются, просто у слайдера значения 8 и 256 и после обновления так и должно быть 8 и 256.

Чекбокс vertical orientation остается checked

> 0 - это значит что шага нет.

Вот здесь шаг есть и равен 1.

![step 0](https://user-images.githubusercontent.com/51824674/88411061-1ae53080-cdf9-11ea-8b7d-44a2adcb4556.gif)

1. Если выставить на панели значение 100, потом обновить страницу, значение на панели останется, фактическое значение изменится, также как и с vertical orientation, синхронизируй панель со слайдером.
2. При изменении шага стрелочками фактически шаг не меняется
![step arrows](https://user-images.githubusercontent.com/51824674/88411380-a363d100-cdf9-11ea-8658-aa8c0462c2b6.gif)
.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Нулевой шаг все еще присутствует, также можно вручную ввести и отрицательный,
![null step](https://user-images.githubusercontent.com/51824674/88550957-1b253c00-d044-11ea-917c-9a3e9c91bd08.gif)

еще можно ввести шаг больше возможного
![big step](https://user-images.githubusercontent.com/51824674/88551688-f67d9400-d044-11ea-9142-6dedd76dde3e.gif)

2. Нужна проверка введенных значений.
![nan](https://user-images.githubusercontent.com/51824674/88551256-7a834c00-d044-11ea-9f4a-d5a3c98de758.gif)

3. Значения сбрасываются на исходные.
![valid off](https://user-images.githubusercontent.com/51824674/88551437-aef70800-d044-11ea-826e-01190f8e34a4.gif)

4. Значение не синхронизируется сразу при включении.
![unsynch](https://user-images.githubusercontent.com/51824674/88551558-cc2bd680-d044-11ea-9cf3-f087c89f42f2.gif)

5. Странно, когда меньшее значение называется максимальным, а большее минимальным, лучше слайдер разворачивать или название менять.
![min-max](https://user-images.githubusercontent.com/51824674/88551863-2e84d700-d045-11ea-80c3-aa73e0c67fc7.gif)

6.
![bug](https://user-images.githubusercontent.com/51824674/88551917-3f354d00-d045-11ea-9a6f-11f2287ae1af.gif)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. При введении недопустимых значений или знака "минус", шаг устанавливается в 0, также при потере фокуса значения не восстанавливаются.
![bad validation](https://user-images.githubusercontent.com/51824674/89104128-bea59080-d438-11ea-8a96-22f30dfdf0ae.gif)

2. Не надо отключать возможность использования отрицательных значений.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Заходим в поле установки шага, устанавливаем шаг в 0, в поле нет изменений, но когда фокус уходит, устанавливается 0.
![Peek 2020-08-09 10-14](https://user-images.githubusercontent.com/51824674/89725903-a9cb8d00-da36-11ea-8c75-c43905edd7c0.gif)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
![Peek 2020-08-15 14-38](https://user-images.githubusercontent.com/51824674/90308884-206bfd00-df05-11ea-8189-387d4463c454.gif)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Ошибка при введении равных min и max.
![Screenshot from 2020-08-25 17-58-09](https://user-images.githubusercontent.com/51824674/91171923-2def6700-e6fd-11ea-8d25-a3f39dccac60.png)

2. Нет проверки типов вводимых значений.
![Screenshot from 2020-08-25 18-02-01](https://user-images.githubusercontent.com/51824674/91171996-4fe8e980-e6fd-11ea-87e9-a575733efb45.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. При введении null в чекбоксы галочка снимается, опция фактически не отключается
![null](https://user-images.githubusercontent.com/51824674/91394947-96088f00-e85c-11ea-9e81-a5b453b26773.png)

2. Для items нужна или валидация, или какая-то другая логика, выглядит странно.
![validate or optional](https://user-images.githubusercontent.com/51824674/91396012-e5e75600-e85c-11ea-9ae6-32dcb2acbfa0.gif)

**Comment by wirwl** [comment]
Исправил, можно проверять.

Дополню. Особенность работы слайдера: если в **Items** 2 и более значений тогда **Items** и **IndexFrom**, **indexTo** используются слайдером. Если в **Items** ноль или одно значение, тогда **Items**, **IndexFrom**, **indexTo** не используются.
