### ISSUE TITLE
Проект не собирается

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinRangeSlider#6]
![Screenshot from 2020-08-09 11-42-34](https://user-images.githubusercontent.com/51824674/89725922-daabc200-da36-11ea-91e7-05f7cb5ad92b.png)

И почему jquery подключается не из node_modules?

**Comment by wirwl** [comment]
У меня собирается.


> И почему jquery подключается не из node_modules?

Просто так сделал, переделаю чтобы из node_modules подключалась.

**Comment by wirwl** [comment]
Исправил. Попробуй собрать проект, может соберёться, но это не точно. ))
Наверное это из-за разных версий node.js, у меня v12.16.3 версия.

**Comment by iatsdotfatr** [comment]
На 12.16.3
![Screenshot from 2020-08-15 14-34-41](https://user-images.githubusercontent.com/51824674/90308826-8310c900-df04-11ea-8c98-daac3bb6e661.png)
![Screenshot from 2020-08-15 14-34-59](https://user-images.githubusercontent.com/51824674/90308829-85732300-df04-11ea-93f1-271d9010cfcd.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Теперь большинство тестов падает и в итоге все равно выходит.
![Screenshot from 2020-08-25 17-42-45](https://user-images.githubusercontent.com/51824674/91170606-f089da00-e6fa-11ea-8ecf-a9e64929c1ad.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
