### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinRangeSlider#7]
1. 
![accessors](https://user-images.githubusercontent.com/51824674/89725976-6e7d8e00-da37-11ea-890a-2f9aac764e1d.png)

2. Использование неименованных обработчиков.
![namelisteners](https://user-images.githubusercontent.com/51824674/89726023-c5836300-da37-11ea-9d59-61b339706fe5.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Лучше обратные кавычки использовать, чтобы плюсы не писать, подключи airbnb-правила
 к линтеру.
![airbnb](https://user-images.githubusercontent.com/51824674/90309498-edc50300-df0a-11ea-91fb-4c132cb97e49.png)

2. Используй деструктуризацию здесь и в подобных местах.
![destr](https://user-images.githubusercontent.com/51824674/90309528-282ea000-df0b-11ea-8a80-2802acb5b6af.png)

3. Здесь else избыточен
![no else](https://user-images.githubusercontent.com/51824674/90309535-367cbc00-df0b-11ea-8ff6-4bb75e9daa5c.png)

4. IIFE здесь используется для создания модуля, но это и так ES6 модуль, так что можно убрать.
![iife](https://user-images.githubusercontent.com/51824674/90309556-64fa9700-df0b-11ea-83cd-d104dc1fda55.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Здесь тоже имеет смысл деструктурировать, часть через let, часть через const
![Screenshot from 2020-08-25 18-50-50](https://user-images.githubusercontent.com/51824674/91176350-fd5efb80-e703-11ea-8588-6652620e3198.png)

2. Лог
![Screenshot from 2020-08-25 18-25-53](https://user-images.githubusercontent.com/51824674/91176445-1c5d8d80-e704-11ea-8435-1ba2cbd6288a.png)

3. Здесь get убрать из названия
![naming 2](https://user-images.githubusercontent.com/51824674/91176629-60e92900-e704-11ea-80be-50b29b22e152.png)

4. Странные названия, и on, и handle сразу. Метод с первой из нижеследующих картинок для чего используется? Отключал его, разницы в работе слайдеров не заметил.
![naming](https://user-images.githubusercontent.com/51824674/91176822-a3ab0100-e704-11ea-865e-3e0efff50a50.png)
![Screenshot from 2020-08-25 18-33-09](https://user-images.githubusercontent.com/51824674/91176793-9857d580-e704-11ea-98c0-60701acc86e3.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.
