### ISSUE TITLE
Функционал

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinRangeSlider#8]
Тултип с текущим значением относится к ползунку, поэтому было бы здорово, чтобы за него тоже можно было перетаскивать
![image](https://user-images.githubusercontent.com/46089168/94942287-c0461000-04de-11eb-80a6-7829e40bd665.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Если взять бегунок не за центр, то при начале движения он к нему все равно возвращается с подергиванием, нужно добавить учет смещения, чтобы если например взять за правый край бегунка, то курсор при перемещении на нем и оставался
![](https://i.imgur.com/SMI6Ip0.gif)

**Comment by wirwl** [comment]
Исправил, можно проверять.
