### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinRangeSlider#9]
Нужно включить строгий режим для TypeScript (strict: true в tsconfig.json), возникнет много ошибок, которые нужно будет поправить. Лучше в процессе еще линтер подключить, чтобы было удобнее смотреть, где какие ошибки есть

**Comment by Fr0stmourne** [comment]
Еще нужно постараться избавиться от использования 'as', в идеале - вообще везде убрать этот оператор

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
От ворнингов лучше тоже по максимуму избавиться, хотя бы указать возвращаемые типы для функций

**Comment by Fr0stmourne** [comment]
Тут не совсем очевидна эта пустая функция с отключением правила
![image](https://user-images.githubusercontent.com/46089168/95070276-8a886d80-0710-11eb-9eff-af971425b183.png)

Если она передается после создания класса, может вот так написать?
![image](https://user-images.githubusercontent.com/46089168/95070430-c4f20a80-0710-11eb-9486-e91e9e152f9b.png)

Еще по типизации функции, для этой функции вроде сигнатура заранее известна, так что лучше прямо ее и сделать типом вместо Function, Function плох тем, что ничего не говорит о принимаемых и возвращаемых значениях

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
> От ворнингов лучше тоже по максимуму избавиться, хотя бы указать возвращаемые типы для функций. От non-null assertion в идеале бы тоже избавиться, на них линтер ругается. Там местами это применяется и для функций даже, может получится чуть удачнее затипизировать?

Этот коммент пропустил, ворнинги еще есть, кое-где на нескольких строчках подряд или на одной строчке цепочкой по 3-4 assertion встречается, нужно по максимуму от этого избавиться

**Comment by wirwl** [comment]
Исправил, можно проверять.
